# Generated by Django 6.0.5 on 2026-06-06 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_suspended'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_suspended', 'User Suspended'), ('user_activated', 'User Activated'), ('user_role_changed', 'User Role Changed'), ('property_approved', 'Property Approved'), ('property_rejected', 'Property Rejected'), ('property_reported', 'Property Reported'), ('property_reported_resolved', 'Property Report Resolved'), ('review_hidden', 'Review Hidden'), ('review_reported', 'Review Reported'), ('review_resolved', 'Review Resolved'), ('dispute_opened', 'Dispute Opened'), ('dispute_reviewing', 'Dispute Under Review'), ('dispute_resolved', 'Dispute Resolved'), ('payment_refunded', 'Payment Refunded')], max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
