# Generated by Django 6.0.5 on 2026-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dispute_resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dispute_status',
            field=models.CharField(choices=[('none', 'None'), ('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved')], default='none', max_length=20),
        ),
    ]
