# Generated by Django 6.0.5 on 2026-06-06 10:33

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    # Change 'admin' and 'Password123!' to your preferred live login details!
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='maimuna_admin',
            email='maimuna@aelithrastay.com',
            password='StaySecure2026!'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_approval_status_property_is_reported_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]