# Generated by Django 6.0.5 on 2026-06-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20260606_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(help_text='Paste a direct image web URL here', max_length=500),
        ),
    ]
