# Generated by Django 6.0.5 on 2026-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('reported', 'Reported'), ('hidden', 'Hidden'), ('resolved', 'Resolved')], default='clean', max_length=20),
        ),
    ]
